"""
Notification model for the Auto Spare Parts ERP system.

This module defines the Notification model which stores per-user notifications
with read/unread status, notification type, and optional metadata.

Satisfies Requirements:
- 16.1: Low stock notification for Storekeeper and Manager roles
- 16.2: Credit limit exceeded notification for Manager and Admin roles
- 16.3: Overdue customer notification for Manager and Admin roles
- 16.4: Pending approval reminder (24+ hours) for Manager and Admin
- 16.5: Store all notifications with read/unread status per user
- 16.6: Support marking notifications as read individually or in bulk
"""

import enum
from datetime import datetime
from typing import Any, Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import BaseModel


class NotificationType(str, enum.Enum):
    """Enumeration of notification types in the ERP system."""

    LOW_STOCK = "low_stock"
    CREDIT_LIMIT_EXCEEDED = "credit_limit_exceeded"
    OVERDUE_CUSTOMER = "overdue_customer"
    PENDING_APPROVAL = "pending_approval"
    SYSTEM = "system"


class Notification(BaseModel):
    """Notification model for storing user notifications.

    Stores notifications generated by system events such as low stock alerts,
    credit limit warnings, overdue customer reminders, and pending approval
    notifications. Each notification is associated with a single user and
    tracks read/unread status.

    Satisfies Requirement 16.5: THE Notification_System SHALL store all
    notifications with read/unread status per user.

    Columns:
        user_id            - FK to the user receiving the notification
        notification_type  - Type of notification (low_stock, credit_limit_exceeded, etc.)
        title              - Short notification title
        message            - Full notification message text
        extra_data         - Optional JSON metadata with context-specific details (column name: metadata)
        is_read            - Whether the notification has been read
        read_at            - Timestamp when the notification was marked as read
    """

    __tablename__ = "notifications"

    # -------------------------------------------------------------------------
    # Foreign Key
    # -------------------------------------------------------------------------
    user_id: Mapped[Any] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
        index=True,
        comment="User who receives this notification",
    )

    # -------------------------------------------------------------------------
    # Notification Content
    # -------------------------------------------------------------------------
    notification_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="Type of notification: low_stock, credit_limit_exceeded, overdue_customer, pending_approval, system",
    )

    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Short notification title",
    )

    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Full notification message text",
    )

    extra_data: Mapped[Optional[dict]] = mapped_column(
        "metadata",
        JSON,
        nullable=True,
        default=None,
        comment="Optional JSON metadata with context-specific details",
    )

    # -------------------------------------------------------------------------
    # Read Status
    # -------------------------------------------------------------------------
    is_read: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether the notification has been read",
    )

    read_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when notification was marked as read",
    )

    # -------------------------------------------------------------------------
    # Indexes
    # -------------------------------------------------------------------------
    __table_args__ = (
        Index(
            "ix_notifications_user_unread",
            "user_id",
            "is_read",
            "created_at",
            postgresql_where=("is_read = false"),
        ),
        Index(
            "ix_notifications_user_created",
            "user_id",
            "created_at",
        ),
    )

    def mark_as_read(self) -> None:
        """Mark this notification as read, setting is_read and read_at."""
        from datetime import timezone

        self.is_read = True
        self.read_at = datetime.now(timezone.utc)

    def __repr__(self) -> str:
        return (
            f"<Notification(id={self.id}, user_id={self.user_id}, "
            f"type='{self.notification_type}', is_read={self.is_read})>"
        )
