"""Apply performance indexing strategy

This migration ensures all performance indexes from the design document are
present in the database. It uses CREATE INDEX IF NOT EXISTS (via op.execute)
for indexes that may already be defined in model __table_args__ and created
by autogenerated migrations.

Indexes created/ensured:
- Partial unique indexes on spare_parts for soft-delete compatibility (Req 18.5, 18.7)
- Composite unique index on stock_status_cache (Req 18.8)
- Composite index on inventory_movement_ledger for reconciliation (Req 18.9)
- Partial composite index on cost_layers for FIFO queries (Req 18.10)
- Index on customer_credit_ledger for balance/aging queries
- Indexes on audit_trail for entity, user, action, date queries
- Indexes on notifications for user unread/date queries
- Index on transfers for status filtering

Revision ID: 0004
Revises: 0003
Create Date: 2025-01-04 00:00:00.000000+00:00
"""
from typing import Sequence, Union

from alembic import op


# Revision identifiers used by Alembic to maintain migration ordering.
revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all performance indexes using IF NOT EXISTS to be idempotent.

    Uses raw SQL via op.execute because:
    1. PostgreSQL's CREATE INDEX IF NOT EXISTS avoids errors when indexes
       already exist (e.g., created by SQLAlchemy model __table_args__).
    2. Partial indexes require WHERE clauses not expressible via op.create_index
       without postgresql_where (which doesn't support IF NOT EXISTS).
    """

    # =========================================================================
    # 1. Partial unique indexes for soft-delete compatibility (Req 18.5, 18.7)
    # =========================================================================
    # These ensure that uniqueness constraints on part_number and barcode only
    # apply to active (non-deleted) records. Soft-deleted records are excluded.

    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uix_spare_parts_part_number_active "
        "ON spare_parts (part_number) WHERE deleted_at IS NULL"
    )

    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uix_spare_parts_barcode_active "
        "ON spare_parts (barcode) WHERE deleted_at IS NULL"
    )

    # =========================================================================
    # 2. Composite unique index on stock_status_cache (Req 18.8)
    # =========================================================================
    # Ensures exactly one cache row per (spare_part_id, location_id) pair.

    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uix_stock_status_cache_part_location "
        "ON stock_status_cache (spare_part_id, location_id)"
    )

    # =========================================================================
    # 3. Composite index on inventory_movement_ledger (Req 18.9)
    # =========================================================================
    # Supports cache reconciliation queries and audit snapshot filtering by
    # enabling efficient range scans on (spare_part_id, location_id, created_at).

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_movement_ledger_part_location_created "
        "ON inventory_movement_ledger (spare_part_id, location_id, created_at)"
    )

    # =========================================================================
    # 4. Partial composite index on cost_layers (Req 18.10)
    # =========================================================================
    # Only indexes layers with remaining stock (remaining_quantity > 0) for
    # efficient FIFO consumption queries ordered by created_at.

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_cost_layers_fifo_lookup "
        "ON cost_layers (spare_part_id, location_id, created_at) "
        "WHERE remaining_quantity > 0"
    )

    # =========================================================================
    # 5. Customer credit ledger index
    # =========================================================================
    # Supports balance calculation (SUM over customer_id) and aging analysis
    # queries filtered by customer_id and ordered by created_at.

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_credit_ledger_customer_created "
        "ON customer_credit_ledger (customer_id, created_at)"
    )

    # =========================================================================
    # 6. Audit trail indexes
    # =========================================================================
    # Support querying by entity (type + id), user, action type, and date range
    # as required by Requirement 15.5.

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_audit_trail_entity "
        "ON audit_trail (entity_type, entity_id)"
    )

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_audit_trail_user_id "
        "ON audit_trail (user_id)"
    )

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_audit_trail_action_type "
        "ON audit_trail (action_type)"
    )

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_audit_trail_created_at "
        "ON audit_trail (created_at)"
    )

    # =========================================================================
    # 7. Notifications indexes
    # =========================================================================
    # Partial index for unread notifications (most common query pattern) and
    # a general index for user notification history ordered by date.

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_notifications_user_unread "
        "ON notifications (user_id, is_read, created_at) "
        "WHERE is_read = false"
    )

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_notifications_user_created "
        "ON notifications (user_id, created_at)"
    )

    # =========================================================================
    # 8. Transfers status index
    # =========================================================================
    # Supports filtering transfers by status (e.g., finding all PENDING or
    # IN_TRANSIT transfers for dashboard/approval views).

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_transfers_status "
        "ON transfers (status)"
    )


def downgrade() -> None:
    """Drop all performance indexes created by this migration.

    Uses DROP INDEX IF EXISTS for safety — some indexes may have been
    dropped by other migrations or may not exist in certain environments.
    """

    # Transfers
    op.execute("DROP INDEX IF EXISTS ix_transfers_status")

    # Notifications
    op.execute("DROP INDEX IF EXISTS ix_notifications_user_created")
    op.execute("DROP INDEX IF EXISTS ix_notifications_user_unread")

    # Audit trail
    op.execute("DROP INDEX IF EXISTS ix_audit_trail_created_at")
    op.execute("DROP INDEX IF EXISTS ix_audit_trail_action_type")
    op.execute("DROP INDEX IF EXISTS ix_audit_trail_user_id")
    op.execute("DROP INDEX IF EXISTS ix_audit_trail_entity")

    # Customer credit ledger
    op.execute("DROP INDEX IF EXISTS ix_credit_ledger_customer_created")

    # Cost layers
    op.execute("DROP INDEX IF EXISTS ix_cost_layers_fifo_lookup")

    # Inventory movement ledger
    op.execute("DROP INDEX IF EXISTS ix_movement_ledger_part_location_created")

    # Stock status cache
    op.execute("DROP INDEX IF EXISTS uix_stock_status_cache_part_location")

    # Spare parts partial unique indexes
    op.execute("DROP INDEX IF EXISTS uix_spare_parts_barcode_active")
    op.execute("DROP INDEX IF EXISTS uix_spare_parts_part_number_active")
